// <auto-generated />
using EastViewTasksAssignment.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EastViewTasksAssignment.DB.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20210428001512_AddingFieldCitizenAlive")]
    partial class AddingFieldCitizenAlive
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EastViewTasksAssigment.DB.Tables.Citizens", b =>
                {
                    b.Property<long>("citizenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("citizenAlive")
                        .HasColumnType("bit");

                    b.Property<string>("citizenIdCard")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("citizenLastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("citizenName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("citizenId");

                    b.HasIndex("citizenIdCard")
                        .IsUnique()
                        .HasFilter("[citizenIdCard] IS NOT NULL");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("EastViewTasksAssigment.DB.Tables.Tasks", b =>
                {
                    b.Property<long>("taskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("taskCitizenId")
                        .HasColumnType("bigint");

                    b.Property<byte>("taskDay")
                        .HasColumnType("tinyint");

                    b.Property<string>("taskDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("taskId");

                    b.HasIndex("taskCitizenId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("EastViewTasksAssigment.DB.Tables.Tasks", b =>
                {
                    b.HasOne("EastViewTasksAssigment.DB.Tables.Citizens", "Citizen")
                        .WithMany("Tasks")
                        .HasForeignKey("taskCitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("EastViewTasksAssigment.DB.Tables.Citizens", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
